### ISSUE TITLE
The user could not log in

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-knowage#6]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error

 47.242.193.105 


# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/118586081-b1da0980-b7cc-11eb-8391-98bac45d8843.png)
![image](https://user-images.githubusercontent.com/83911329/118586095-b7375400-b7cc-11eb-81b8-2cd04890a89d.png)
![image](https://user-images.githubusercontent.com/83911329/118586710-cec30c80-b7cd-11eb-9df7-77135e8f34e6.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
docker ps
![image](https://user-images.githubusercontent.com/43192516/118597613-7d237d80-b7df-11eb-8ccc-0ccd3e016e1a.png)

**Comment by qiaofeng1227** [comment]
docker logs knowage-server
```
18-May-2021 03:24:54.603 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/home/knowage/apache-tomcat/webapps/knowagekpiengine] has finished in [15,515] ms
18-May-2021 03:24:58.618 INFO [localhost-startStop-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
18-May-2021 03:24:58.690 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/home/knowage/apache-tomcat/webapps/knowagetalendengine] has finished in [9,210] ms
18-May-2021 03:24:58.697 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-May-2021 03:24:58.717 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-8009"]
18-May-2021 03:24:58.728 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 129744 ms
2021-05-18 03:56:41.459  INFO 1 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-05-18 03:56:41.462  INFO 1 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
modifyHandshake() Current thread http-nio-8080-exec-5
modifyHandshake() Current thread http-nio-8080-exec-15
modifyHandshake() Current thread http-nio-8080-exec-11
modifyHandshake() Current thread http-nio-8080-exec-11
modifyHandshake() Current thread http-nio-8080-exec-6
18-May-2021 04:25:07.586 INFO [http-nio-8080-exec-5] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [2380x00ll|'|'|SGFjS2VkX0Q3NUU2QUFB|'|'|WIN-QZN7FJ7D1O|'|'|Administrator|'|'|18-11-28|'|'||'|'|Win ]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:431)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:503)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1629)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by qiaofeng1227** [comment]
you can logined in by random password of mysql
![image](https://user-images.githubusercontent.com/43192516/118598045-1c487500-b7e0-11eb-914a-96ba928bae0b.png)

**Comment by qiaofeng1227** [comment]
```
[root@iZj6cavtctajcry7veuiahZ data]# git clone --depth=1 https://github.com/Websoft9/docker-knowage.git
Cloning into 'docker-knowage'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 40 (delta 5), reused 24 (delta 1), pack-reused 0
Unpacking objects: 100% (40/40), done.
[root@iZj6cavtctajcry7veuiahZ data]# cd docker-knowage/
[root@iZj6cavtctajcry7veuiahZ docker-knowage]# ls
CHANGELOG.md  CONTRIBUTING.md  docker-compose-production.yml  Knowage-Python-Docker  Knowage-R-Docker  knowage-server  LICENSE  LICENSE.md  Notes.md  README.md  README-zh.md  variables.json
[root@iZj6cavtctajcry7veuiahZ docker-knowage]# docker-compose -f docker-compose-production.yml  up -d
```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/118773310-4a4cb880-b8b7-11eb-9f4b-3880d9794b12.png)

**Comment by zengxc-1996** [comment]
This is a bug with the official image, so I can't fix it now, refer to it here:

https://github.com/KnowageLabs/Knowage-Server-Docker/issues/47

**Comment by qiaofeng1227** [comment]
Done

**Comment by qiaofeng1227** [comment]
Amazon ubuntu20.04 need 15minutes

**Comment by qiaofeng1227** [comment]
Done
